Style/HashSyntax:
  EnforcedShorthandSyntax: either
Style/StringLiterals:
  EnforcedStyle: double_quotes
Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "*.gemspec"
Metrics/ClassLength:
  Enabled: false
Metrics/MethodLength:
  Max: 20
require:
  - rubocop-rspec
