name: Release Docker image

on:
  push:
    tags:
      - "v**"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Strip v prefix
        run: |
          TAG=${{ github.event.release.tag_name }}
          echo "MIHARI_VERSION=${TAG#v}" >> $GITHUB_ENV
      - name: Build Docker image
        run: |
          docker build . \
          --tag ghcr.io/$GITHUB_ACTOR/mihari:latest \
          --tag ghcr.io/$GITHUB_ACTOR/mihari:${{ env.MIHARI_VERSION }} \
          --build-arg MIHARI_VERSION=${{ env.MIHARI_VERSION }}
      - name: Push Docker image
        run: |
          docker push ghcr.io/$GITHUB_ACTOR/mihari:latest
          docker push ghcr.io/$GITHUB_ACTOR/mihari:${{ env.MIHARI_VERSION }}
