name: Release Docker image

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker image
        run: |
          docker build --tag ghcr.io/$GITHUB_ACTOR/mihari:latest \
          --tag ghcr.io/$GITHUB_ACTOR/mihari:${{ github.event.release.tag_name }} \
          .
      - name: Push Docker image
        run: |
          docker push ghcr.io/$GITHUB_ACTOR/mihari:latest
          docker push ghcr.io/$GITHUB_ACTOR/mihari:${{ github.event.release.tag_name }}
