name: Ruby CI

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.7
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.7
    - name: Build and test with Rake
      env:
        DATABASE: postgresql://postgres:postgres@localhost:5432/test
      run: |
        sudo apt-get -yqq install libpq-dev
        gem install bundler
        bundle install
        bundle exec rake